language: csharp
solution: Sellix.net.sln
mono: none
dotnet: 3.1.10
install:
  - dotnet restore
script:
  - dotnet build
  - dotnet test 
  if: branch = master
  - dotnet pack ./Sellix.net/Sellix.Net.csproj -c Release