language: csharp
solution: Sellix.net.sln
mono: none
os: linux
dotnet: 3.1.10
install:
  - dotnet restore
script:
  - dotnet build
  - dotnet test 
deploy: 
 skip_cleanup: true
 provider: script
 script: bash ./release.sh $NUGET_API_KEY
 on: 
   branch: master
